### ISSUE TITLE
'Close this Listing' button for Owner only AND the winner sees "You have won this Auction" if he is the highest bidder

### ISSUE THREAD

**Issue by Khaan787** [Khaan787/commerce#3]
On **listing.html** the code `{% if user == owner and listing.Auction_closed == False %}` does not seems to work where I am trying to display the **'Close this Listing'** button only to the owner IF the `listing.Auction_closed == False`, BUT IF `{% elif user == owner and listing.Auction_closed == True %}` then the owner sees this: `<p> You have closed this Auction </p>`

On **index.html** the code `{% if listing.Auction_closed == True and winner %}` does not seem to work where I am trying to display `<p> You have won this Auction.</p>` IF the auction is closed and the one viewing the page is the winner of the auction, if it NOT closed then **'Place a Bid'**  form is shown

**Comment by bsassoli** [comment]
There is a very silly bug in your code. Just a typo, basically. try adding the following to `index.html`:
```
{% block body %}

<p> User: {{user}} </p>
<p> Owner: {{owner}} </p>
<p> Auction closed: {{ listing.Auction_closed }} </p>
```

You will notice that `listing.Auction_closed` doesn't return anything. Can you see why?

**Comment by Khaan787** [comment]
I can't figure out why.!  :(

**Comment by Khaan787** [comment]
> {% block body %}
> 
> <p> User: {{user}} </p>
> <p> Owner: {{owner}} </p>
> <p> Auction closed: {{ listing.Auction_closed }} </p>
> ```
> 
So I have fixed the above on `listing.html` but I don't know why would the same not work for `index.html`

**Comment by bsassoli** [comment]
It’s that.listing…. Not listing hahaha 

Inviato da iPad

**Comment by Khaan787** [comment]
ok so this fixes it:
```    
    <p> User: {{user}} </p>
    <p> Owner: {{listing.listing_owner}} </p>
    <p> Auction closed: {{ listing.Auction_closed }} </p>
```

Why would the previous one not work

> It’s that.listing…. Not listing hahaha Inviato da iPad
> […](#)

Yes just did that 😆

**Comment by Khaan787** [comment]
For `index.html`, this works for the `owner`:

```
<p> User: {{user}} </p>
<p> Owner: {{listing.listing_owner}} </p>
<p> Auction closed: {{ listing.Auction_closed }} </p>
```

But this doesn't:
```
<p> User: {{user}} </p>
<p> Owner: {{owner}} </p>
<p> Auction closed: {{ listing.Auction_closed }} </p>
```

Even though I am giving access to the template for these values in `views.py`:

```
    return render(request, "auctions/index.html",{
        "listing": listing,
        "user" : request.user,
        "owner": owner,          
        "winner": winner
    })
```

**WHY.?**

**Comment by bsassoli** [comment]
I would have to check, probably the way you pass data to the template. But now I can’t….

Inviato da iPad

**Comment by Khaan787** [comment]
Ok :)

Thank you soo much @bsassoli , so grateful to you

**Comment by Khaan787** [comment]
> For `index.html`, this works for the `owner`:
> 
> ```
> <p> User: {{user}} </p>
> <p> Owner: {{listing.listing_owner}} </p>
> <p> Auction closed: {{ listing.Auction_closed }} </p>
> ```
> 
> But this doesn't:
> 
> ```
> <p> User: {{user}} </p>
> <p> Owner: {{owner}} </p>
> <p> Auction closed: {{ listing.Auction_closed }} </p>
> ```
> 
> Even though I am giving access to the template for these values in `views.py`:
> 
> ```
>     return render(request, "auctions/index.html",{
>         "listing": listing,
>         "user" : request.user,
>         "owner": owner,          
>         "winner": winner
>     })
> ```
> 
> **WHY.?**


So what I found out is that, in `close_auction` view the data that I am trying to pass to the template is not getting passed at all. Only the data from the `index` view is getting passed to the template i.e `"listings": Listing.objects.all()`.

Why is that and How do I fix it.?

**Comment by bsassoli** [comment]
You have a wrong indentation in the return block of `close_auction`. The view only returns if the `request.method` is POST.

**Comment by Khaan787** [comment]
Fixed the indentation before as well, but it wasn't working. Did it again, but still not working

**Comment by Khaan787** [comment]
After the indentation the values under the for loop doesn't gets implemented when clicked on "Close Listing" button.

**Comment by bsassoli** [comment]
Works fine for me... 

```
@login_required
def close_auction(request,listing_id):
    listing = Listing.objects.get(pk=listing_id)
    starting_Bid = listing.Starting_Bid        
    Bids_amounts =listing.bids.values_list('Bid_amount', flat=True)

    Highest_bid = None
    winner_object = None
    winner = None
    
    if request.method == "POST":
        listing.Auction_closed = True
        listing.save()

        # Find which Bid_amount is == to the Starting_Bid i.e which Bid_amount is the Highest Bid placed 
        # Find the corresponding bid_placed_by of that Bid_amount
        for i in Bids_amounts:
            if i == starting_Bid:
                Highest_bid = i
                winner_object = Bid.objects.get(Bid_amount=Highest_bid)
                winner = winner_object.bid_placed_by

    # The index page of the Highest bidder should get a message of "You won the Bid" on That Listing
    return render(request, "auctions/index.html",{
        "user" : request.user,
        "listing": listing,
        "winner": winner
    })
```

**Comment by bsassoli** [comment]
by the way I would suggest not to use variables that start with a capital letter except for classes

**Comment by Khaan787** [comment]
I think I am getting all the values I require to implement the intended functionality. You can see as below:


![Screenshot 2022-05-09 at 10 08 14 PM](https://user-images.githubusercontent.com/59615325/167461728-f8a34cb3-a18e-45f1-b630-559a16d4f9ee.png)
![Screenshot 2022-05-09 at 10 09 15 PM](https://user-images.githubusercontent.com/59615325/167461745-88ee22c9-7f04-4b5e-8aee-8d9ece4313d4.png)

The only problem is that the values from the `return` block is not getting passed to the `index.html` template and hence I can't see the values of `owner` and `winner` on the index page:

![Screenshot 2022-05-09 at 10 13 15 PM](https://user-images.githubusercontent.com/59615325/167462322-51306522-9473-4e37-bfb5-f60450e198b5.png)

`Bids_amounts =listing.bids.values_list('Bid_amount', flat=True)` gives me a list of the **AMOUNTS** bided on **THAT** particular **Listing** **ONLY**, so when I say `for i in Bids_amounts` it LOOPS through the AMOUNTS placed on **THAT** particular **Listing** **ONLY**. And since `starting_Bid` is always the highest bid, therefore, `Highest_bid = i` and ultimately: 
`winner_object = Bid.objects.get(Bid_amount=Highest_bid)`  And
`winner = winner_object.bid_placed_by`

Similarly when I say ` Bids_Placers = listing.bids.values_list('bid_placed_by', flat=True)` it gives me list of **USERS** who have made a Bid on **THAT** particular **Listing** **ONLY**

I don't know what exactly am I missing here.?

Can you please make the changes in code and push it here.?
